export { default as Dashboard } from "./dashboard/Dashboard.jsx"
export { default as MirHassan } from "./mirhassan/MirHassan.jsx"
export { default as NadeemSarwar } from "./nadeem sarwar/NadeemSarwar.jsx"
export { default as Farhan } from "./farhan/Farhan.jsx"
export { default as AliJee } from "./alijee/AliJee.jsx"
export { default as AliShanawar } from "./alishanawar/AliShanawar.jsx"
export { default as IrfanHaider } from "./irfanhaider/IrfanHaider.jsx"
export { default as RazaAbbas } from "./razaabbas/RazaAbbas.jsx"
export { default as MesumAbbas } from "./mesumabbas/MesumAbbas.jsx"
export { default as Noha } from "./noha/Noha.jsx"